const db = [
  {
    id: '1',
    nombre: "Jardines del Hípico II",
    año: "2021",
    superficie: "45m²",
    tipo: "Casa / Vivienda",
    descripcion: "Esta casa ha sido diseñada y construida de manera personalizada, según las necesidades y preferencias específicas del cliente. El proceso de diseño ha sido llevado a cabo por un equipo de arquitectos y diseñadores que trabajan en estrecha colaboración con el cliente para entender sus requerimientos y crear una vivienda que se adapte a su estilo de vida y personalidad. El diseño personalizado permite una mayor flexibilidad y creatividad en el proceso de construcción, lo que significa que cada detalle, desde la distribución de los espacios hasta la selección de los materiales y acabados, se ha considerado cuidadosamente para satisfacer las necesidades y gustos del cliente. El resultado final es una casa única y personalizada que refleja la individualidad del cliente",
    seleccionada: true,
    images:[
      "/images/obras/Obra 01/01.jpg",    
      "/images/obras/Obra 01/08.jpg",    
      "/images/obras/Obra 01/02.jpg",    
      "/images/obras/Obra 01/03.jpg",    
      "/images/obras/Obra 01/04.jpg",    
      "/images/obras/Obra 01/05.jpg",    
      "/images/obras/Obra 01/06.jpg",    
      "/images/obras/Obra 01/07.jpg",    
      "/images/obras/Obra 01/09.jpg"    
    ]
  },
  {
    id: '2',
    nombre: "Jardines del Hípico III",
    año: "2021",
    superficie: "110m²",
    tipo: "Casa / Vivienda",
    descripcion: "Esta casa ha sido diseñada y construida teniendo en cuenta el objetivo de maximizar el valor de renta mensual para el propietario, con un presupuesto específico para la obra. La tipología de la casa se ha seleccionado cuidadosamente para lograr este objetivo, tomando en cuenta las necesidades y preferencias del mercado de alquiler.",
    seleccionada: false,
    images:[
      "/images/obras/Obra 02/01.jpg",    
      "/images/obras/Obra 02/02.jpg",    
      "/images/obras/Obra 02/03.jpg",    
      "/images/obras/Obra 02/04.jpg",    
      "/images/obras/Obra 02/05.jpg",    
      "/images/obras/Obra 02/06.jpg",    
      "/images/obras/Obra 02/07.jpg",    
      "/images/obras/Obra 02/08.jpg",    
      "/images/obras/Obra 02/09.jpg",     
      "/images/obras/Obra 02/10.jpg",     
      "/images/obras/Obra 02/11.jpg",     
      "/images/obras/Obra 02/12.jpg",     
      "/images/obras/Obra 02/13.jpg"     
    ]
  },
  {
    id: '3',
    nombre: "Jardines del Hípico IV",
    año: "2021",
    superficie: "110m²",
    tipo: "Casa / Vivienda",
    descripcion: "Esta casa ha sido diseñada y construida teniendo en cuenta el objetivo de maximizar el valor de renta mensual para el propietario, con un presupuesto específico para la obra. La tipología de la casa se ha seleccionado cuidadosamente para lograr este objetivo, tomando en cuenta las necesidades y preferencias del mercado de alquiler.",
    seleccionada: false,
    images:[
      "/images/obras/Obra 03/01.jpg",    
      "/images/obras/Obra 03/02.jpg",    
      "/images/obras/Obra 03/03.jpg",    
      "/images/obras/Obra 03/04.jpg",    
      "/images/obras/Obra 03/05.jpg",    
      "/images/obras/Obra 03/06.jpg",    
      "/images/obras/Obra 03/07.jpg",    
      "/images/obras/Obra 03/08.jpg",    
      "/images/obras/Obra 03/09.jpg"     
    ]
  },
  {
    id: '4',
    nombre: "Valle Escondido",
    año: "2021",
    superficie: "110m²",
    tipo: "Casa / Vivienda",
    descripcion: "casa ha sido diseñada y desarrollada con el objetivo principal de ser comercializada en el mercado inmobiliario. Para lograrlo, se ha llevado a cabo un análisis de mercado exhaustivo y una segmentación precisa de los posibles compradores, para entender sus necesidades y preferencias y crear una oferta que satisfaga sus expectativas. El diseño de la casa se ha optimizado para ofrecer un equilibrio entre funcionalidad, estética y rentabilidad, utilizando materiales y acabados de alta calidad pero dentro de un presupuesto específico para la obra. Esto ha permitido maximizar el valor de la propiedad sin exceder el precio de venta deseado.",
    seleccionada: false,
    images:[
      "/images/obras/Obra 04/01.jpg",    
      "/images/obras/Obra 04/02.jpg",    
      "/images/obras/Obra 04/03.jpg",    
      "/images/obras/Obra 04/04.jpg",    
      "/images/obras/Obra 04/05.jpg",    
      "/images/obras/Obra 04/06.jpg",    
      "/images/obras/Obra 04/07.jpg",    
      "/images/obras/Obra 04/08.jpg",    
      "/images/obras/Obra 04/09.jpg",       
      "/images/obras/Obra 04/10.jpg",       
      "/images/obras/Obra 04/11.jpg",       
      "/images/obras/Obra 04/12.jpg",       
      "/images/obras/Obra 04/13.jpg",       
      "/images/obras/Obra 04/14.jpg",       
    ]
  },
  {
    id: '5',
    nombre: "Villa Albertina",
    año: "2022",
    superficie: "100m²",
    tipo: "Casa / Vivienda",
    descripcion: "Esta casa ha sido diseñada y construida de manera personalizada, según las necesidades y preferencias específicas del cliente. El proceso de diseño ha sido llevado a cabo por un equipo de arquitectos y diseñadores que trabajan en estrecha colaboración con el cliente para entender sus requerimientos y crear una vivienda que se adapte a su estilo de vida y personalidad. El diseño personalizado permite una mayor flexibilidad y creatividad en el proceso de construcción, lo que significa que cada detalle, desde la distribución de los espacios hasta la selección de los materiales y acabados, se ha considerado cuidadosamente para satisfacer las necesidades y gustos del cliente. El resultado final es una casa única y personalizada que refleja la individualidad del cliente",
    seleccionada: true,
    images:[
      "/images/obras/Obra 05/01.jpg",    
      "/images/obras/Obra 05/02.jpg",    
      "/images/obras/Obra 05/03.jpg",    
      "/images/obras/Obra 05/04.jpg",    
      "/images/obras/Obra 05/05.jpg",    
      "/images/obras/Obra 05/06.jpg",    
      "/images/obras/Obra 05/07.jpg",    
      "/images/obras/Obra 05/08.jpg",    
      "/images/obras/Obra 05/09.jpg",       
      "/images/obras/Obra 05/10.jpg",       
      "/images/obras/Obra 05/11.jpg",       
      "/images/obras/Obra 05/12.jpg",       
      "/images/obras/Obra 05/13.jpg",       
      "/images/obras/Obra 05/14.jpg",       
    ]
  },
  {
    id: '6',
    nombre: "Vista Verde I",
    año: "2020",
    superficie: "140m²",
    tipo: "Casa / Vivienda",
    descripcion: "Esta casa ha sido diseñada y construida de manera personalizada, según las necesidades y preferencias específicas del cliente. El proceso de diseño ha sido llevado a cabo por un equipo de arquitectos y diseñadores que trabajan en estrecha colaboración con el cliente para entender sus requerimientos y crear una vivienda que se adapte a su estilo de vida y personalidad. El diseño personalizado permite una mayor flexibilidad y creatividad en el proceso de construcción, lo que significa que cada detalle, desde la distribución de los espacios hasta la selección de los materiales y acabados, se ha considerado cuidadosamente para satisfacer las necesidades y gustos del cliente. El resultado final es una casa única y personalizada que refleja la individualidad del cliente",
    seleccionada: false,
    images:[
      "/images/obras/Obra 06/01.jpg",    
      "/images/obras/Obra 06/02.jpg",    
      "/images/obras/Obra 06/03.jpg",    
      "/images/obras/Obra 06/04.jpg",    
      "/images/obras/Obra 06/05.jpg",    
      "/images/obras/Obra 06/06.jpg",    
      "/images/obras/Obra 06/07.jpg",    
      "/images/obras/Obra 06/08.jpg",    
      "/images/obras/Obra 06/09.jpg",       
      "/images/obras/Obra 06/10.jpg",       
      "/images/obras/Obra 06/11.jpg",       
      "/images/obras/Obra 06/12.jpg",       
      "/images/obras/Obra 06/13.jpg",       
      "/images/obras/Obra 06/14.jpg",   
      "/images/obras/Obra 06/15.jpg",   
      "/images/obras/Obra 06/16.jpg",   
      "/images/obras/Obra 06/17.jpg",   
      "/images/obras/Obra 06/18.jpg",   
      "/images/obras/Obra 06/19.jpg",   
      "/images/obras/Obra 06/20.jpg",   
      "/images/obras/Obra 06/21.jpg",   
      "/images/obras/Obra 06/22.jpg",   
      "/images/obras/Obra 06/23.jpg",   
      "/images/obras/Obra 06/24.jpg",   
      "/images/obras/Obra 06/25.jpg",   
      "/images/obras/Obra 06/26.jpg",   
      "/images/obras/Obra 06/27.jpg",   
    ]
  },
  {
    id: '7',
    nombre: "Vista Verde II",
    año: "2020",
    superficie: "120m²",
    tipo: "Casa / Vivienda",
    descripcion: "Esta casa ha sido diseñada y construida de manera personalizada, según las necesidades y preferencias específicas del cliente. El proceso de diseño ha sido llevado a cabo por un equipo de arquitectos y diseñadores que trabajan en estrecha colaboración con el cliente para entender sus requerimientos y crear una vivienda que se adapte a su estilo de vida y personalidad. El diseño personalizado permite una mayor flexibilidad y creatividad en el proceso de construcción, lo que significa que cada detalle, desde la distribución de los espacios hasta la selección de los materiales y acabados, se ha considerado cuidadosamente para satisfacer las necesidades y gustos del cliente. El resultado final es una casa única y personalizada que refleja la individualidad del cliente",
    seleccionada: true,
    images:[
      "/images/obras/Obra 07/01.jpg",    
      "/images/obras/Obra 07/02.jpg",    
      "/images/obras/Obra 07/03.jpg",    
      "/images/obras/Obra 07/04.jpg",    
      "/images/obras/Obra 07/05.jpg",    
      "/images/obras/Obra 07/06.jpg",    
      "/images/obras/Obra 07/07.jpg",    
      "/images/obras/Obra 07/08.jpg",    
      "/images/obras/Obra 07/09.jpg",      
      "/images/obras/Obra 07/10.jpg",      
      "/images/obras/Obra 07/11.jpg",      
      "/images/obras/Obra 07/12.jpg",      
      "/images/obras/Obra 07/13.jpg",      
      "/images/obras/Obra 07/14.jpg"      
    ]
  },
  {
    id: '8',
    nombre: "Aguas Claras I",
    año: "2021",
    superficie: "140m²",
    tipo: "Casa / Vivienda",
    descripcion: "Esta casa ha sido diseñada y construida de manera personalizada, según las necesidades y preferencias específicas del cliente. El proceso de diseño ha sido llevado a cabo por un equipo de arquitectos y diseñadores que trabajan en estrecha colaboración con el cliente para entender sus requerimientos y crear una vivienda que se adapte a su estilo de vida y personalidad. El diseño personalizado permite una mayor flexibilidad y creatividad en el proceso de construcción, lo que significa que cada detalle, desde la distribución de los espacios hasta la selección de los materiales y acabados, se ha considerado cuidadosamente para satisfacer las necesidades y gustos del cliente. El resultado final es una casa única y personalizada que refleja la individualidad del cliente",
    seleccionada: false,
    images:[
      "/images/obras/Obra 08/01.jpg",    
      "/images/obras/Obra 08/02.jpg",    
      "/images/obras/Obra 08/03.jpg",    
      "/images/obras/Obra 08/04.jpg",    
      "/images/obras/Obra 08/05.jpg",    
      "/images/obras/Obra 08/06.jpg",    
      "/images/obras/Obra 08/07.jpg",    
      "/images/obras/Obra 08/08.jpg",    
      "/images/obras/Obra 08/09.jpg"      
    ]
  },
  {
    id: '9',
    nombre: "Aguas Claras II",
    año: "2021",
    superficie: "82m²",
    tipo: "Casa / Vivienda",
    descripcion: "Esta casa ha sido diseñada y construida de manera personalizada, según las necesidades y preferencias específicas del cliente. El proceso de diseño ha sido llevado a cabo por un equipo de arquitectos y diseñadores que trabajan en estrecha colaboración con el cliente para entender sus requerimientos y crear una vivienda que se adapte a su estilo de vida y personalidad. El diseño personalizado permite una mayor flexibilidad y creatividad en el proceso de construcción, lo que significa que cada detalle, desde la distribución de los espacios hasta la selección de los materiales y acabados, se ha considerado cuidadosamente para satisfacer las necesidades y gustos del cliente. El resultado final es una casa única y personalizada que refleja la individualidad del cliente",
    seleccionada: false,
    images:[
      "/images/obras/Obra 09/01.jpg",    
      "/images/obras/Obra 09/02.jpg",    
      "/images/obras/Obra 09/03.jpg",    
      "/images/obras/Obra 09/04.jpg",    
      "/images/obras/Obra 09/05.jpg",    
      "/images/obras/Obra 09/06.jpg",    
      "/images/obras/Obra 09/07.jpg",    
      "/images/obras/Obra 09/08.jpg",    
      "/images/obras/Obra 09/09.jpg",      
      "/images/obras/Obra 09/10.jpg",      
      "/images/obras/Obra 09/11.jpg",      
      "/images/obras/Obra 09/12.jpg",      
    ]
  },
]

export default db





