const db = [
  {
    id: '1',
    nombre: "Jardines del Hípico II",
    año: "2021",
    superficie: "45m²",
    tipo: "Casa / Vivienda",
    descripcion: "Casa diseñada y construida de manera personalizada. El proceso de diseño ha sido llevado a cabo por un equipo de arquitectos y diseñadores, en estrecha colaboración con el cliente para entender sus requerimientos y así crear una vivienda que se adapte a su estilo de vida y personalidad. El resultado final es una casa única, ya que el diseño personalizado permite una mayor flexibilidad y creatividad en el proceso de construcción, lo que significa que cada detalle, desde la distribución de los espacios hasta la selección de los materiales y acabados, se ha considerado cuidadosamente.",
    seleccionada: true,
    images:[
      "/images/obras/obra_01/01.jpg",    
      "/images/obras/obra_01/08.jpg",    
      "/images/obras/obra_01/02.jpg",    
      "/images/obras/obra_01/03.jpg",    
      "/images/obras/obra_01/04.jpg",    
      "/images/obras/obra_01/05.jpg",    
      "/images/obras/obra_01/06.jpg",    
      "/images/obras/obra_01/07.jpg",    
      "/images/obras/obra_01/09.jpg"    
    ]
  },
  {
    id: '2',
    nombre: "Jardines del Hípico III",
    año: "2021",
    superficie: "110m²",
    tipo: "Casa / Vivienda",
    descripcion: "Esta casa ha sido diseñada y construida teniendo en cuenta el objetivo de maximizar el valor de renta mensual para el propietario, con un presupuesto específico para la obra. La tipología de la casa se ha seleccionado cuidadosamente para lograr este objetivo, tomando en cuenta las necesidades y preferencias del mercado de alquiler.",
    seleccionada: false,
    images:[
      "/images/obras/obra_02/01.jpg",    
      "/images/obras/obra_02/02.jpg",    
      "/images/obras/obra_02/03.jpg",    
      "/images/obras/obra_02/04.jpg",    
      "/images/obras/obra_02/05.jpg",    
      "/images/obras/obra_02/06.jpg",    
      "/images/obras/obra_02/07.jpg",    
      "/images/obras/obra_02/08.jpg",    
      "/images/obras/obra_02/09.jpg",     
      "/images/obras/obra_02/10.jpg",     
      "/images/obras/obra_02/11.jpg",     
      "/images/obras/obra_02/12.jpg",     
      "/images/obras/obra_02/13.jpg"     
    ]
  },
  {
    id: '3',
    nombre: "Jardines del Hípico IV",
    año: "2021",
    superficie: "110m²",
    tipo: "Casa / Vivienda",
    descripcion: "Esta casa ha sido diseñada y construida teniendo en cuenta el objetivo de maximizar el valor de renta mensual para el propietario, con un presupuesto específico para la obra. La tipología de la casa se ha seleccionado cuidadosamente para lograr este objetivo, tomando en cuenta las necesidades y preferencias del mercado de alquiler.",
    seleccionada: false,
    images:[
      "/images/obras/obra_03/01.jpg",    
      "/images/obras/obra_03/02.jpg",    
      "/images/obras/obra_03/03.jpg",    
      "/images/obras/obra_03/04.jpg",    
      "/images/obras/obra_03/05.jpg",    
      "/images/obras/obra_03/06.jpg",    
      "/images/obras/obra_03/07.jpg",    
      "/images/obras/obra_03/08.jpg",    
      "/images/obras/obra_03/09.jpg"     
    ]
  },
  {
    id: '4',
    nombre: "Valle Escondido",
    año: "2021",
    superficie: "110m²",
    tipo: "Casa / Vivienda",
    descripcion: "casa ha sido diseñada y desarrollada con el objetivo principal de ser comercializada en el mercado inmobiliario. Para lograrlo, se ha llevado a cabo un análisis de mercado exhaustivo y una segmentación precisa de los posibles compradores, para entender sus necesidades y preferencias y crear una oferta que satisfaga sus expectativas. El diseño de la casa se ha optimizado para ofrecer un equilibrio entre funcionalidad, estética y rentabilidad, utilizando materiales y acabados de alta calidad pero dentro de un presupuesto específico para la obra. Esto ha permitido maximizar el valor de la propiedad sin exceder el precio de venta deseado.",
    seleccionada: false,
    images:[
      "/images/obras/obra_04/01.jpg",    
      "/images/obras/obra_04/02.jpg",    
      "/images/obras/obra_04/03.jpg",    
      "/images/obras/obra_04/04.jpg",    
      "/images/obras/obra_04/05.jpg",    
      "/images/obras/obra_04/06.jpg",    
      "/images/obras/obra_04/07.jpg",    
      "/images/obras/obra_04/08.jpg",    
      "/images/obras/obra_04/09.jpg",       
      "/images/obras/obra_04/10.jpg",       
      "/images/obras/obra_04/11.jpg",       
      "/images/obras/obra_04/12.jpg",       
      "/images/obras/obra_04/13.jpg",       
      "/images/obras/obra_04/14.jpg",       
    ]
  },
  {
    id: '5',
    nombre: "Villa Albertina",
    año: "2022",
    superficie: "100m²",
    tipo: "Casa / Vivienda",
    descripcion: "Esta casa ha sido diseñada y construida de manera personalizada, según las necesidades y preferencias específicas del cliente. El proceso de diseño ha sido llevado a cabo por un equipo de arquitectos y diseñadores que trabajan en estrecha colaboración con el cliente para entender sus requerimientos y crear una vivienda que se adapte a su estilo de vida y personalidad. El diseño personalizado permite una mayor flexibilidad y creatividad en el proceso de construcción, lo que significa que cada detalle, desde la distribución de los espacios hasta la selección de los materiales y acabados, se ha considerado cuidadosamente para satisfacer las necesidades y gustos del cliente. El resultado final es una casa única y personalizada que refleja la individualidad del cliente",
    seleccionada: true,
    images:[
      "/images/obras/obra_05/01.jpg",    
      "/images/obras/obra_05/02.jpg",    
      "/images/obras/obra_05/03.jpg",    
      "/images/obras/obra_05/04.jpg",    
      "/images/obras/obra_05/05.jpg",    
      "/images/obras/obra_05/06.jpg",    
      "/images/obras/obra_05/07.jpg",    
      "/images/obras/obra_05/08.jpg",    
      "/images/obras/obra_05/09.jpg",       
      "/images/obras/obra_05/10.jpg",       
      "/images/obras/obra_05/11.jpg",       
      "/images/obras/obra_05/12.jpg",       
      "/images/obras/obra_05/13.jpg",       
      "/images/obras/obra_05/14.jpg",       
    ]
  },
  {
    id: '6',
    nombre: "Vista Verde I",
    año: "2020",
    superficie: "140m²",
    tipo: "Casa / Vivienda",
    descripcion: "Esta casa ha sido diseñada y construida de manera personalizada, según las necesidades y preferencias específicas del cliente. El proceso de diseño ha sido llevado a cabo por un equipo de arquitectos y diseñadores que trabajan en estrecha colaboración con el cliente para entender sus requerimientos y crear una vivienda que se adapte a su estilo de vida y personalidad. El diseño personalizado permite una mayor flexibilidad y creatividad en el proceso de construcción, lo que significa que cada detalle, desde la distribución de los espacios hasta la selección de los materiales y acabados, se ha considerado cuidadosamente para satisfacer las necesidades y gustos del cliente. El resultado final es una casa única y personalizada que refleja la individualidad del cliente",
    seleccionada: false,
    images:[
      "/images/obras/obra_06/01.jpg",    
      "/images/obras/obra_06/02.jpg",    
      "/images/obras/obra_06/03.jpg",    
      "/images/obras/obra_06/04.jpg",    
      "/images/obras/obra_06/05.jpg",    
      "/images/obras/obra_06/06.jpg",    
      "/images/obras/obra_06/07.jpg",    
      "/images/obras/obra_06/08.jpg",    
      "/images/obras/obra_06/09.jpg",       
      "/images/obras/obra_06/10.jpg",       
      "/images/obras/obra_06/11.jpg",       
      "/images/obras/obra_06/12.jpg",       
      "/images/obras/obra_06/13.jpg",       
      "/images/obras/obra_06/14.jpg",   
      "/images/obras/obra_06/15.jpg",   
      "/images/obras/obra_06/16.jpg",   
      "/images/obras/obra_06/17.jpg",   
      "/images/obras/obra_06/18.jpg",   
      "/images/obras/obra_06/19.jpg",   
      "/images/obras/obra_06/20.jpg",   
      "/images/obras/obra_06/21.jpg",   
      "/images/obras/obra_06/22.jpg",   
      "/images/obras/obra_06/23.jpg",   
      "/images/obras/obra_06/24.jpg",   
      "/images/obras/obra_06/25.jpg",   
      "/images/obras/obra_06/26.jpg",   
      "/images/obras/obra_06/27.jpg",   
    ]
  },
  {
    id: '7',
    nombre: "Vista Verde II",
    año: "2020",
    superficie: "120m²",
    tipo: "Casa / Vivienda",
    descripcion: "Esta casa ha sido diseñada y construida de manera personalizada, según las necesidades y preferencias específicas del cliente. El proceso de diseño ha sido llevado a cabo por un equipo de arquitectos y diseñadores que trabajan en estrecha colaboración con el cliente para entender sus requerimientos y crear una vivienda que se adapte a su estilo de vida y personalidad. El diseño personalizado permite una mayor flexibilidad y creatividad en el proceso de construcción, lo que significa que cada detalle, desde la distribución de los espacios hasta la selección de los materiales y acabados, se ha considerado cuidadosamente para satisfacer las necesidades y gustos del cliente. El resultado final es una casa única y personalizada que refleja la individualidad del cliente",
    seleccionada: true,
    images:[
      "/images/obras/obra_07/01.jpg",    
      "/images/obras/obra_07/02.jpg",    
      "/images/obras/obra_07/03.jpg",    
      "/images/obras/obra_07/04.jpg",    
      "/images/obras/obra_07/05.jpg",    
      "/images/obras/obra_07/06.jpg",    
      "/images/obras/obra_07/07.jpg",    
      "/images/obras/obra_07/08.jpg",    
      "/images/obras/obra_07/09.jpg",      
      "/images/obras/obra_07/10.jpg",      
      "/images/obras/obra_07/11.jpg",      
      "/images/obras/obra_07/12.jpg",      
      "/images/obras/obra_07/13.jpg",      
      "/images/obras/obra_07/14.jpg"      
    ]
  },
  {
    id: '8',
    nombre: "Aguas Claras I",
    año: "2021",
    superficie: "140m²",
    tipo: "Casa / Vivienda",
    descripcion: "Esta casa ha sido diseñada y construida de manera personalizada, según las necesidades y preferencias específicas del cliente. El proceso de diseño ha sido llevado a cabo por un equipo de arquitectos y diseñadores que trabajan en estrecha colaboración con el cliente para entender sus requerimientos y crear una vivienda que se adapte a su estilo de vida y personalidad. El diseño personalizado permite una mayor flexibilidad y creatividad en el proceso de construcción, lo que significa que cada detalle, desde la distribución de los espacios hasta la selección de los materiales y acabados, se ha considerado cuidadosamente para satisfacer las necesidades y gustos del cliente. El resultado final es una casa única y personalizada que refleja la individualidad del cliente",
    seleccionada: false,
    images:[
      "/images/obras/obra_08/01.jpg",    
      "/images/obras/obra_08/02.jpg",    
      "/images/obras/obra_08/03.jpg",    
      "/images/obras/obra_08/04.jpg",    
      "/images/obras/obra_08/05.jpg",    
      "/images/obras/obra_08/06.jpg",    
      "/images/obras/obra_08/07.jpg",    
      "/images/obras/obra_08/08.jpg",    
      "/images/obras/obra_08/09.jpg"      
    ]
  },
  {
    id: '9',
    nombre: "Aguas Claras II",
    año: "2021",
    superficie: "82m²",
    tipo: "Casa / Vivienda",
    descripcion: "Esta casa ha sido diseñada y construida de manera personalizada, según las necesidades y preferencias específicas del cliente. El proceso de diseño ha sido llevado a cabo por un equipo de arquitectos y diseñadores que trabajan en estrecha colaboración con el cliente para entender sus requerimientos y crear una vivienda que se adapte a su estilo de vida y personalidad. El diseño personalizado permite una mayor flexibilidad y creatividad en el proceso de construcción, lo que significa que cada detalle, desde la distribución de los espacios hasta la selección de los materiales y acabados, se ha considerado cuidadosamente para satisfacer las necesidades y gustos del cliente. El resultado final es una casa única y personalizada que refleja la individualidad del cliente",
    seleccionada: false,
    images:[
      "/images/obras/obra_09/01.jpg",    
      "/images/obras/obra_09/02.jpg",    
      "/images/obras/obra_09/03.jpg",    
      "/images/obras/obra_09/04.jpg",    
      "/images/obras/obra_09/05.jpg",    
      "/images/obras/obra_09/06.jpg",    
      "/images/obras/obra_09/07.jpg",    
      "/images/obras/obra_09/08.jpg",    
      "/images/obras/obra_09/09.jpg",      
      "/images/obras/obra_09/10.jpg",      
      "/images/obras/obra_09/11.jpg",      
      "/images/obras/obra_09/12.jpg",      
    ]
  },
]

export default db





